version: "3.1"
services:
  homepage:
    restart: always
    build:
      context: "."
      dockerfile: ./Dockerfile
    image: blog
    container_name: blog
    ports:
      - 8900:80
    volumes:
      - /app/node_modules
      - .:/app
